---
title: "Homework 5"
author: "Alice Tivarovsky"
date: "11/3/2019"
output: github_document
---

## Setup Code

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

```

## Problem 1

Pulling in iris: 

```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

iris_with_missing
```

Writing a function that fills in missing values:


```{r}
output = vector("list", length = 5)

# generate a logical vector, output
for (i in 1:5) {
  output[[i]] = is.numeric(iris_with_missing[[i]])
}
output

# if output = true, run a loop, calculating mean in each vector, then replacing blanks with the mean 

```


```{r}
output = vector("list", length = 5)

for (i in 1:5) {
  
  if (is.numeric(iris_with_missing[[i]])) {
    
    x = iris_with_missing[[i]] %>% mean(na.rm = TRUE)
    iris_with_missing[[i]] %>% replace(is.na(iris_with_missing[[i]]), x)
    
  } else if (is.character(iris_with_missing[[i]])) {
    iris_with_missing[[i]] %>% replace(is.na(iris_with_missing[[i]]), "virginica")
  }
  
}

```

Try defining a function: 

```{r}

iris_replace = function(x){
  
  if (is.numeric(x)) {
    y = mean(x, na.rm = TRUE)
    x = replace(x, is.na(x), y)
  } else if (is.character(x)) {
    x = replace(x, is.na(x), "virginica")
  }
}

```

Now, apply the function to a for loop.

```{r}
output = vector("list", length = 5)

for (i in 1:5) {
  
  output[[i]] = iris_replace(iris_with_missing[[i]])
  
}

output = map_df(iris_with_missing, iris_replace)

output
```




